config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  devise_for :users
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  get "postsearch" => "searches#postsearch"
  get "bookstag" => "searches#tagsearch"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end 
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end 
  resources :direct_messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
    delete "all_destroy" => "groups#all_destroy"
  end
  resources :tags do
    get 'books', to: 'books#search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  #DM
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  
  has_one_attached :profile_image
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  #フォローいた時の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  #フォローを外す時の処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  #フォローしているか判断
  def following?(user)
    followings.include?(user)
  end
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @current_user_entry = Entry.where(user_id: current_user)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id then
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
    @books = @user.books
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @week_book = @books.created_week
    @week_ago_book = @books.created_week_ago
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      @books = Book.all
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>
          フォロー数:<%= user.followings.count %>
        </td>
        <td>
          フォロワー数:<%= user.followers.count %>
        </td>
        <% if current_user != user %>
          <td>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          </td>
          <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>follwers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>
<div>
  <% if user == current_user %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% end %>
  <% unless user == current_user %>
    <% if current_user.following?(user) && user.following?(current_user) %>
      <% if @is_room == true %>
        <%= link_to "Roomへ", room_path(@room_id), class:"btn btn-primary" %>
      <% else %>
        <%= form_with model: @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, value: user.id %>
          <% end %>
          <%= f.submit "DMを送る", class:"btn btn-primary" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>
　
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_post_details.html.erb
<h3>投稿数の前日比・前週比</h3>
<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th>今日の投稿数</th>
      <th>前日の投稿数</th>
      <th>前日比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= @today_book.count %>
      </td>
      <td>
        <%= @yesterday_book.count %>
      </td>
      <td> <!-- 1÷0は出来ないから前日の投稿数が0の時は計算しない -->
        <% if @yesterday_book.count == 0 %>
          前日の投稿はありません
        <% else %>
          <% @the_day_before_ratio = @today_book.count / @yesterday_book.count.to_f %>
          <%= (@the_day_before_ratio*100).round %>%
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th>今週の投稿数</th>
      <th>前週の投稿数</th>
      <th>前週比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= @week_book.count %>
      </td>
      <td>
        <%= @week_ago_book.count %>
      </td>
      <td> <!-- 1÷0は出来ないから先週の投稿数が0の時は計算しない -->
        <% if @week_ago_book.count == 0 %>
          前日の投稿はありません
        <% else %>
          <% @the_week_before_ratio = @week_book.count / @week_ago_book.count.to_f %>
          <%= (@the_week_before_ratio*100).round %>%
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<h3>7日間分の投稿数</h3>
<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th>6日前</th>
      <th>5日前</th>
      <th>4日前</th>
      <th>3日前</th>
      <th>2日前</th>
      <th>1日前</th>
      <th>今日</th>      
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= books.created_6_days_ago.count %>
      </td>
      <td>
        <%= books.created_5_days_ago.count %>
      </td>
      <td>
        <%= books.created_4_days_ago.count %>
      </td>
      <td>
        <%= books.created_3_days_ago.count %>
      </td>
      <td>
        <%= books.created_2_days_ago.count %>
      </td>
      <td>
        <%= @yesterday_book.count %>
      </td>
      <td>
        <%= @today_book.count %>
      </td>
    </tr>
  </tbody>
</table>
<canvas id="myLineChart"></canvas>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
  <script>
    var ctx = document.getElementById('myLineChart');
    var myLineChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
        datasets: [{
          label: '投稿した本の数',
          data: [ <%= books.created_6_days_ago.count %>,
                  <%= books.created_5_days_ago.count %>,
                  <%= books.created_4_days_ago.count %>,
                  <%= books.created_3_days_ago.count %>,
                  <%= books.created_2_days_ago.count %>,
                  <%= @yesterday_book.count %>,
                  <%= @today_book.count %>
                ],
          borderColor: "rgba(0,0,255,1)",
          backgroundColor: "rgba(0,0,0,0)",
          pointBackgroundColor: "rgba(0,0,255,1)"
        }]
      },
      options: {
        title: {
          display: true,
          text: '7日間の投稿数の比較'
        },
        scales: {
          yAxes: [{
            ticks: {
              suggestedMin: 0,
              stepSize: 1
            }
          }]
        }
      }
    });
  </script>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <div class="d-flex justify-content-between">
        <div>
          <h2>Users</h2>
        </div>
        <div>
          <%= link_to "グループ作成", new_group_path, class:"btn btn-primary" %>
          |
          <%= link_to "グループ一覧", groups_path, class: "btn btn-success" %>
        </div>
      </div>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <div class="search_form" >
        <%= form_with url: postsearch_path, local: false, method: :get do |f| %>
          <%= f.hidden_field :user_id, value: @user.id %>
          <%= f.date_field :created_at %>
          <%= f.submit "検索", id: "submit" %>
        <% end %>
        <div id="search-results"></div>
      <%= render 'post_details', books: @books %>
    </div>
  </div>
</div>