config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  devise_for :users
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  get "postsearch" => "searches#postsearch"
  get "bookstag" => "searches#tagsearch"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end 
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end 
  resources :direct_messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
    delete "all_destroy" => "groups#all_destroy"
  end
  resources :tags do
    get 'books', to: 'books#search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  is_impressionable
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end
    new_tags.each do |new|
      new_book_tag = Tag.find_or_create_by(name: new)
      self.tags << new_book_tag
    end
  end 
  
  #投稿数取得
  #今日
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  #昨日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  #2~6日前
  scope :created_2_days_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3_days_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4_days_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5_days_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6_days_ago, -> { where(created_at: 6.day.ago.all_day) }
  #今週
  scope :created_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  #先週
  scope :created_week_ago, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  
  #新着順
  scope :latest, -> { order(created_at: :desc) }
  #score順
  scope :score_count, ->{ order(score: :desc) }
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  
  impressionist :action => [:show]

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user
    @book_new = Book.new
    @post_comment = PostComment.new
    impressionist(@book, nil, unique: [:session_hash])
  end

  def index
    if params[:latest]
      @books = Book.latest
    elsif params[:score_count]
      @books = Book.score_count
    else
      @books = week_book_favorited
    end 
    @tag_list = Tag.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:name].split(nil)
    if @book.save
      @book.save_tag(tag_list)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      @user = @book.user
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @books = @tag.books.all
  end 
  
  private

  def book_params
    params.require(:book).permit(:title, :body, :score)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end
  
  def week_book_favorited
    Book.includes(:favorited_books).
      sort {|a,b|
        b.favorited_books.includes(:favorites).where(created_at: Time.current.all_week).size <=>
        a.favorited_books.includes(:favorites).where(created_at: Time.current.all_week).size
      }
  end 

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div id="post_raty">評価:</div>
  <script>
    let elem = document.querySelector('#post_raty');
    let opt = {
      size : 36,
      starOff: '<%= asset_path('star-off.png') %>',
      starOn: '<%= asset_path('star-on.png') %>',
      scoreName: 'book[score]',
    };
    raty(elem,opt);
  </script>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to book.user do %>
            <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td class="favorite-btn-<%= book.id %>">
          <%= render 'favorites/favorite-btn', book: book %>
        </td>
        <td>
          <% book.tags.each do |tag| %>
            <%=link_to tag.name, tag_books_path(tag.id) %>
          <% end %>
        </td>
        <td>
          <div id="post_raty<%= book.id%>"></div>
          <script>
            let elem<%= book.id %> = document.querySelector('#post_raty<%= book.id%>');
            let opt<%= book.id %> = {
              readOnly: true,
              size: 36,
              starOff: '<%= asset_path('star-off.png') %>',
              starOn: '<%= asset_path('star-on.png') %>',
              score: <%= book.score %>,
            };
            raty(elem<%= book.id %>, opt<%= book.id %>)
          </script>
        </td>
        <td>
          コメント数:<%= book.post_comments.count %>
        </td>
        <td>
          閲覧数:<%= book.impressionist_count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @book %>
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <p>
        <%= link_to "新着順", books_path(latest: "true") %>
        |
        <%= link_to "評価順", books_path(score_count: "true") %>
      </p>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/search.html.erb
<h2>Books search for "<%= @tag.name %>"</h2>
<div>
  <%= render "books/index", books: @books %>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td class="favorite-btn-<%= @book.id %>">
            <%= render 'favorites/favorite-btn', book: @book %>
          </td>
          <td>
            <% @book.tags.each do |tag| %>
              <%=link_to tag.name, tag_books_path(tag.id) %>
            <% end %>
          </td>
          <td>
            <div id="post_raty<%= @book.id%>"></div>
            <script>
              let elem<%= @book.id %> = document.querySelector('#post_raty<%= @book.id%>');
              let opt<%= @book.id %> = {
                readOnly: true,
                size: 36,
                starOff: '<%= asset_path('star-off.png') %>',
                starOn: '<%= asset_path('star-on.png') %>',
                score: <%= @book.score %>,
              };
              raty(elem<%= @book.id %>, opt<%= @book.id %>)
            </script>
          </td>
          <% if current_user == @book.user %>
            <td>
              <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %>
              <br>
              <%= link_to 'Destroy', book_path, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
            </td>
          <% end %>
          <td>
            コメント数:<%= @book.post_comments.count %>
            <br>
            閲覧数:<%= @book.impressionist_count %>
          </td>
        </tr>
      </table>
      <div class="post-comment-<%= @post_comment.id %>">
        <%= render 'post_comments/post_comment', book: @book, post_comment: @post_comment %>
      </div>
    </div>
  </div>
</div>